/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpotifyCallbackRouteImport } from './routes/spotify.callback'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppPlaylistsRouteImport } from './routes/_app/playlists'
import { Route as AppLibraryRouteImport } from './routes/_app/library'
import { Route as AppConnectRouteImport } from './routes/_app/connect'
import { Route as ApiSpotifyCallbackRouteImport } from './routes/api.spotify.callback'
import { Route as AppPlaylistsIdRouteImport } from './routes/_app/playlists.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotifyCallbackRoute = SpotifyCallbackRouteImport.update({
  id: '/spotify/callback',
  path: '/spotify/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaylistsRoute = AppPlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectRoute = AppConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AppRoute,
} as any)
const ApiSpotifyCallbackRoute = ApiSpotifyCallbackRouteImport.update({
  id: '/api/spotify/callback',
  path: '/api/spotify/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPlaylistsIdRoute = AppPlaylistsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPlaylistsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/connect': typeof AppConnectRoute
  '/library': typeof AppLibraryRoute
  '/playlists': typeof AppPlaylistsRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/spotify/callback': typeof SpotifyCallbackRoute
  '/playlists/$id': typeof AppPlaylistsIdRoute
  '/api/spotify/callback': typeof ApiSpotifyCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/connect': typeof AppConnectRoute
  '/library': typeof AppLibraryRoute
  '/playlists': typeof AppPlaylistsRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/spotify/callback': typeof SpotifyCallbackRoute
  '/playlists/$id': typeof AppPlaylistsIdRoute
  '/api/spotify/callback': typeof ApiSpotifyCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_app/connect': typeof AppConnectRoute
  '/_app/library': typeof AppLibraryRoute
  '/_app/playlists': typeof AppPlaylistsRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/spotify/callback': typeof SpotifyCallbackRoute
  '/_app/playlists/$id': typeof AppPlaylistsIdRoute
  '/api/spotify/callback': typeof ApiSpotifyCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/connect'
    | '/library'
    | '/playlists'
    | '/settings'
    | '/spotify/callback'
    | '/playlists/$id'
    | '/api/spotify/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/connect'
    | '/library'
    | '/playlists'
    | '/settings'
    | '/spotify/callback'
    | '/playlists/$id'
    | '/api/spotify/callback'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/_app/connect'
    | '/_app/library'
    | '/_app/playlists'
    | '/_app/settings'
    | '/spotify/callback'
    | '/_app/playlists/$id'
    | '/api/spotify/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  SpotifyCallbackRoute: typeof SpotifyCallbackRoute
  ApiSpotifyCallbackRoute: typeof ApiSpotifyCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spotify/callback': {
      id: '/spotify/callback'
      path: '/spotify/callback'
      fullPath: '/spotify/callback'
      preLoaderRoute: typeof SpotifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/playlists': {
      id: '/_app/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof AppPlaylistsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connect': {
      id: '/_app/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof AppConnectRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/spotify/callback': {
      id: '/api/spotify/callback'
      path: '/api/spotify/callback'
      fullPath: '/api/spotify/callback'
      preLoaderRoute: typeof ApiSpotifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/playlists/$id': {
      id: '/_app/playlists/$id'
      path: '/$id'
      fullPath: '/playlists/$id'
      preLoaderRoute: typeof AppPlaylistsIdRouteImport
      parentRoute: typeof AppPlaylistsRoute
    }
  }
}

interface AppPlaylistsRouteChildren {
  AppPlaylistsIdRoute: typeof AppPlaylistsIdRoute
}

const AppPlaylistsRouteChildren: AppPlaylistsRouteChildren = {
  AppPlaylistsIdRoute: AppPlaylistsIdRoute,
}

const AppPlaylistsRouteWithChildren = AppPlaylistsRoute._addFileChildren(
  AppPlaylistsRouteChildren,
)

interface AppRouteChildren {
  AppConnectRoute: typeof AppConnectRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppPlaylistsRoute: typeof AppPlaylistsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConnectRoute: AppConnectRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppPlaylistsRoute: AppPlaylistsRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  SpotifyCallbackRoute: SpotifyCallbackRoute,
  ApiSpotifyCallbackRoute: ApiSpotifyCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
